# Generated by Django 3.1.2 on 2020-10-25 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewExperience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='additional_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='compensation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='no_of_rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='university_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
