# Generated by Django 3.1.2 on 2020-11-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewExperience', '0002_auto_20201025_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='no_of_rounds',
            field=models.IntegerField(default=1),
        ),
    ]
